# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ AltoroJ-3.2 ]
  pull_request:
    branches: [ AltoroJ-3.2 ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'temurin'
    - name: Build with Gradle
      uses: gradle/gradle-build-action@4137be6a8bf7d7133955359dbd952c0ca73b1021
      with:
        arguments: build
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: altoromutual
        path: '**/**.war'
  
  apiiro:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - run: |
          curl -vvv -X POST "$APIIRO_URL/v1/cicd/builds" \
          -H "Authorization: ${{ secrets.APIIRO_TOKEN }}" \
          -H 'Content-Type: application/json' \
          --data '{ 
                    "buildId": "$BUILD_ID",
                    "sourceCommit": "$COMMIT_SHA",
                    "repositoryKey": "$REPOSITORY_KEY",
                    "applicationName": "$PRODUCT_NAME",
                    "buildPageUrl": "$BUILD_PAGE_URL" 
                  }'
      env:
        COMMIT_SHA: ${{ github.sha }}
        BUILD_ID: ${{ github.run_id }}
        VERSION_STRING: 123
        BUILD_PAGE_URL: '${{ github.server_url }}/${{ github.repository	 }}/actions/runs/${{ github.run_id }}'
        PRODUCT_NAME: AltoroJ
        APIIRO_TOKEN: ${{ secrets.APIIRO_TOKEN }}
        APIIRO_URL: https://app.apiiro.com
        REPOSITORY_KEY: https___github_com_patrickapiiro__AltoroJ__AltoroJ